apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: team-based-care-dev
stringData:
  DB_PASSWORD: CHANGE_THIS
  KEYCLOAK_IMPORT_CLIENT_SECRET_BIDAN: CHANGE_THIS
  KEYCLOAK_IMPORT_CLIENT_SECRET_CADRE: CHANGE_THIS
  KEYCLOAK_IMPORT_CLIENT_SECRET_FHIR_SERVER_AUTH: CHANGE_THIS
  KEYCLOAK_IMPORT_CLIENT_SECRET_FHIR_WEB: CHANGE_THIS
  KEYCLOAK_IMPORT_CLIENT_SECRET_OPENFN: CHANGE_THIS
  KEYCLOAK_IMPORT_CLIENT_SECRET_OPENSRP_V2: CHANGE_THIS
  KEYCLOAK_IMPORT_CLIENT_SECRET_VACCINATOR: CHANGE_THIS
  KEYCLOAK_PASSWORD: CHANGE_THIS
