apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/backend-config: '{"default": "fhir-server-backend-config"}'
    cloud.google.com/neg: '{"ingress":true}'
    cloud.google.com/neg-status: '{"network_endpoint_groups":{"8080":"k8s1-ca21d307-team-based-care-d-fhir-gateway-servi-808-3bd6af71"},"zones":["asia-southeast2-b","asia-southeast2-c"]}'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"cloud.google.com/backend-config":"{\"default\": \"fhir-server-backend-config\"}","cloud.google.com/neg":"{\"ingress\":true}","cloud.google.com/neg-status":"{\"network_endpoint_groups\":{\"8080\":\"k8s1-ca21d307-team-based-care-d-fhir-gateway-servi-808-3bd6af71\"},\"zones\":[\"asia-southeast2-a\",\"asia-southeast2-b\",\"asia-southeast2-c\"]}"},"creationTimestamp":"2023-12-07T07:45:44Z","labels":{"app":"fhir-gateway"},"name":"fhir-gateway-service","namespace":"team-based-care-dev","resourceVersion":"121678028","uid":"aef40d08-2f25-414f-a83d-9fda78d5c25c"},"spec":{"clusterIP":"34.118.234.2","clusterIPs":["34.118.234.2"],"internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"8080-to-8080-tcp","port":8080,"protocol":"TCP","targetPort":8080}],"selector":{"app":"fhir-gateway"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
  creationTimestamp: "2023-12-07T07:45:44Z"
  labels:
    app: fhir-gateway
  name: fhir-gateway-service
  namespace: team-based-care-dev
  resourceVersion: "470243086"
  uid: aef40d08-2f25-414f-a83d-9fda78d5c25c
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8080-to-8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: fhir-gateway
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
