apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/backend-config: '{"default": "fhir-server-backend-config"}'
    cloud.google.com/neg: '{"ingress":true}'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"cloud.google.com/backend-config":"{\"default\": \"fhir-server-backend-config\"}","cloud.google.com/neg":"{\"ingress\":true}"},"creationTimestamp":"2023-12-07T07:45:44Z","labels":{"app":"fhir-server"},"name":"fhir-server-service","namespace":"team-based-care-dev","resourceVersion":"175174101","uid":"66900a12-dd2a-4a36-850b-1a0d1b617d8b"},"spec":{"clusterIP":"34.118.227.101","clusterIPs":["34.118.227.101"],"internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"port":8080,"protocol":"TCP","targetPort":8080}],"selector":{"app":"fhir-server"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
  creationTimestamp: "2023-12-07T07:45:44Z"
  labels:
    app: fhir-server
  name: fhir-server-service
  namespace: team-based-care-dev
  resourceVersion: "175237157"
  uid: 66900a12-dd2a-4a36-850b-1a0d1b617d8b
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: fhir-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
